cmake_minimum_required(VERSION 3.22)

function(pnx_ioc_get_value ioc_lines key out_var)
    set(prefix "${key}=")
    foreach(line ${ioc_lines})
        if(line STREQUAL "" OR line MATCHES "^#")
            continue()
        endif()
        string(LENGTH "${prefix}" prefix_len)
        string(LENGTH "${line}" line_len)
        if(line_len GREATER prefix_len)
            string(SUBSTRING "${line}" 0 ${prefix_len} line_prefix)
            if(line_prefix STREQUAL "${prefix}")
                math(EXPR value_start "${prefix_len}")
                string(SUBSTRING "${line}" ${value_start} -1 value)
                set(${out_var} "${value}" PARENT_SCOPE)
                return()
            endif()
        endif()
    endforeach()
    set(${out_var} "" PARENT_SCOPE)
endfunction()

function(pnx_ioc_parse ioc_file)
    if(NOT EXISTS "${ioc_file}")
        message(FATAL_ERROR "IOC file not found: ${ioc_file}")
    endif()

    file(READ "${ioc_file}" ioc_content)
    string(REPLACE "\r\n" "\n" ioc_content "${ioc_content}")
    string(REPLACE "\r" "\n" ioc_content "${ioc_content}")
    string(REPLACE "\n" ";" ioc_lines "${ioc_content}")

    set(can_hw "")
    set(uart_hw "")
    set(has_usb_fs FALSE)
    set(has_usb_hs FALSE)

    foreach(line ${ioc_lines})
        if(line MATCHES "^Mcu\\.IP[0-9]+=((FDCAN|CAN)[0-9]+)$")
            list(APPEND can_hw "${CMAKE_MATCH_1}")
        elseif(line MATCHES "^Mcu\\.IP[0-9]+=((USART|UART|LPUART)[0-9]+)$")
            list(APPEND uart_hw "${CMAKE_MATCH_1}")
        elseif(line STREQUAL "Mcu.IPNb")
            continue()
        elseif(line MATCHES "^Mcu\\.IP[0-9]+=USB_OTG_FS$")
            set(has_usb_fs TRUE)
        elseif(line MATCHES "^Mcu\\.IP[0-9]+=USB_OTG_HS$")
            set(has_usb_hs TRUE)
        endif()
    endforeach()

    list(SORT can_hw)
    list(SORT uart_hw)
    list(REMOVE_DUPLICATES can_hw)
    list(REMOVE_DUPLICATES uart_hw)

    pnx_natural_sort_hw("${can_hw}" can_hw)
    pnx_natural_sort_hw("${uart_hw}" uart_hw)

    if(has_usb_fs OR has_usb_hs)
        set(has_usb TRUE)
    else()
        set(has_usb FALSE)
    endif()

    set(PNX_IOC_CAN_HW "${can_hw}" PARENT_SCOPE)
    set(PNX_IOC_UART_HW "${uart_hw}" PARENT_SCOPE)
    set(PNX_IOC_LINES "${ioc_lines}" PARENT_SCOPE)
    set(PNX_IOC_HAS_USB_FS "${has_usb_fs}" PARENT_SCOPE)
    set(PNX_IOC_HAS_USB_HS "${has_usb_hs}" PARENT_SCOPE)
    set(PNX_IOC_HAS_USB "${has_usb}" PARENT_SCOPE)
endfunction()

function(pnx_ioc_uart_index uart_hw_list hw_name out_var)
    string(TOLOWER "${hw_name}" hw_lower)
    set(index -1)
    set(i 0)
    foreach(hw ${uart_hw_list})
        string(TOLOWER "${hw}" entry_lower)
        if(entry_lower STREQUAL hw_lower)
            set(index ${i})
            break()
        endif()
        math(EXPR i "${i} + 1")
    endforeach()
    set(${out_var} "${index}" PARENT_SCOPE)
endfunction()

function(pnx_ioc_hw_in_list hw_list hw_name out_var)
    pnx_ioc_uart_index("${hw_list}" "${hw_name}" index)
    if(index GREATER_EQUAL 0)
        set(${out_var} TRUE PARENT_SCOPE)
    else()
        set(${out_var} FALSE PARENT_SCOPE)
    endif()
endfunction()

function(pnx_ioc_fdcan_frame_format ioc_lines hw out_var)
    string(TOUPPER "${hw}" hw_upper)
    if(hw_upper MATCHES "^CAN[0-9]+$")
        set(${out_var} "classic" PARENT_SCOPE)
        return()
    endif()
    pnx_ioc_get_value("${ioc_lines}" "${hw_upper}.FrameFormat" frame_format)
    if(frame_format STREQUAL "FDCAN_FRAME_FD_BRS" OR frame_format STREQUAL "FDCAN_FRAME_FD_NO_BRS")
        set(${out_var} "fd" PARENT_SCOPE)
    else()
        set(${out_var} "classic" PARENT_SCOPE)
    endif()
endfunction()

function(pnx_ioc_fdcan_ext_filters ioc_lines hw out_var)
    string(TOUPPER "${hw}" hw_upper)
    pnx_ioc_get_value("${ioc_lines}" "${hw_upper}.ExtFiltersNbr" ext_filters)
    if(ext_filters STREQUAL "")
        set(ext_filters "0")
    endif()
    set(${out_var} "${ext_filters}" PARENT_SCOPE)
endfunction()

function(pnx_ioc_fdcan_std_filters ioc_lines hw out_var)
    string(TOUPPER "${hw}" hw_upper)
    pnx_ioc_get_value("${ioc_lines}" "${hw_upper}.StdFiltersNbr" std_filters)
    if(std_filters STREQUAL "")
        set(std_filters "0")
    endif()
    set(${out_var} "${std_filters}" PARENT_SCOPE)
endfunction()

function(pnx_ioc_uart_has_dma ioc_lines hw direction out_var)
    string(TOUPPER "${hw}" hw_upper)
    set(found FALSE)
    foreach(line ${ioc_lines})
        if(line MATCHES "^Dma\\.Request[0-9]+=${hw_upper}_${direction}$")
            set(found TRUE)
        endif()
    endforeach()
    set(${out_var} "${found}" PARENT_SCOPE)
endfunction()

function(pnx_hw_to_handle hw out_var)
    string(TOLOWER "${hw}" hw_lower)
    if(hw_lower MATCHES "^usart([0-9]+)$")
        set(${out_var} "&huart${CMAKE_MATCH_1}" PARENT_SCOPE)
    elseif(hw_lower MATCHES "^uart([0-9]+)$")
        set(${out_var} "&huart${CMAKE_MATCH_1}" PARENT_SCOPE)
    elseif(hw_lower MATCHES "^lpuart([0-9]+)$")
        set(${out_var} "&hlpuart${CMAKE_MATCH_1}" PARENT_SCOPE)
    else()
        set(${out_var} "&h${hw_lower}" PARENT_SCOPE)
    endif()
endfunction()

function(pnx_hw_to_dma_handle hw direction out_var)
    string(TOLOWER "${hw}" hw_lower)
    string(TOLOWER "${direction}" dir_lower)
    set(${out_var} "&hdma_${hw_lower}_${dir_lower}" PARENT_SCOPE)
endfunction()

function(pnx_to_json_bool cmake_bool out_var)
    if(cmake_bool)
        set(${out_var} "true" PARENT_SCOPE)
    else()
        set(${out_var} "false" PARENT_SCOPE)
    endif()
endfunction()

function(pnx_natural_sort_hw hw_list out_var)
    set(keys "")
    foreach(hw ${hw_list})
        string(TOUPPER "${hw}" hw_upper)
        if(hw_upper MATCHES "^(FDCAN|CAN|USART|UART|LPUART)([0-9]+)$")
            set(prefix "${CMAKE_MATCH_1}")
            set(num "${CMAKE_MATCH_2}")
            string(LENGTH "${num}" num_len)
            math(EXPR pad_len "3 - ${num_len}")
            if(pad_len LESS 0)
                set(pad_len 0)
            endif()
            string(REPEAT "0" ${pad_len} padding)
            set(key "${prefix}_${padding}${num}")
        else()
            set(key "${hw_upper}")
        endif()
        list(APPEND keys "${key}:${hw}")
    endforeach()
    list(SORT keys)
    set(sorted "")
    foreach(entry ${keys})
        string(REGEX REPLACE "^[^:]+:(.*)$" "\\1" hw "${entry}")
        list(APPEND sorted "${hw}")
    endforeach()
    set(${out_var} "${sorted}" PARENT_SCOPE)
endfunction()
